# Generated by Django 4.2 on 2025-01-23 08:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2025, 1, 23, 8, 31, 41, 810647), editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2025, 1, 23, 8, 31, 41, 810660))),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.base')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            bases=('products.base',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.base')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('price', models.FloatField(default=1.0)),
                ('stock', models.IntegerField(default=0)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            bases=('products.base',),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.base')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('products.base',),
        ),
    ]
