# Generated by Django 4.2 on 2025-01-23 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='base',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 23, 8, 50, 14, 561394), editable=False),
        ),
        migrations.AlterField(
            model_name='base',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 23, 8, 50, 14, 561407)),
        ),
    ]
